---
title: "p8105_hw4_ym2771"
author: "Yuqi Miao"
date: "11/2/2019"
output: github_document
---


# Problem 1

```{r,message=FALSE}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
fill_missing <- function(vec){
    if (is.character(vec[1])) {
        vec = ifelse(is.na(vec), "virginica",vec)
    }else{
        if (is.numeric(vec)) {
            mean = mean(vec,na.rm = T)
            vec = ifelse(is.na(vec), mean,vec)
        }else{
            vec = vec
        }
    }
        
}

iris_fill_NA <- map(iris_with_missing,fill_missing) %>% bind_cols()
iris_fill_NA    

```

# Problem 2

```{r,message=FALSE}
file_names <- paste("data/",list.files("data"),sep = "")
study_df <- 
    map(file_names,read_csv) %>% 
    bind_rows() %>% 
    mutate(group_number = str_sub(file_names,6,11),
           ID = row_number()) %>% 
    pivot_longer(cols = 1:8, names_to = "week",names_prefix = "week_",values_to = "value") %>% 
    separate(col = group_number,c("group","number"),sep = '_') %>% 
    mutate(week = factor(as.numeric(week), levels = 1:8),
           group = factor(group,levels = c("con","exp"))) %>% 
    select(ID,everything(),-number)
```


```{r}
study_df %>% 
    ggplot(aes(x = week,y = value,color = group, group = ID))+
    geom_line()
  
  
```

## comment
 Value of experiment group is significantly larger than control group.


# Problem 3


```{r}
sim_reg <- function(beta1 = 1){
    n = 30
    beta0 = 2
    var = 50
    x = rnorm(n)
    y = beta0 + beta1*x + rnorm(n,0,sqrt(var))
    ls_fit = broom::tidy(lm(y~x,))
    ls_fit %>% filter(term == "x") %>% select(estimate,p.value)
    
}

estimationa_beta1_1 <- 
    rerun(10000,sim_reg()) %>% 
    bind_rows()


estimation <- 
    tibble(
        beta1 = 1:6
    ) %>% 
    mutate(out_list = map(.x = beta1, ~rerun(10000,sim_reg(.x))),
           out_df = map(out_list, bind_rows)) %>% 
    select(-out_list) %>% 
    unnest(out_df)
```


```{r}
g1 <- estimation %>% 
  filter(p.value<0.05) %>% 
  group_by(beta1) %>% 
  summarise(count = n(),proportion = count/10000) %>% 
  ggplot(aes(x = beta1, y = proportion))+
  geom_bar(stat = "identity")+
  labs(y = "Proportion of rejection( P-value < 0.05)", title = "Power of different effective size")

g1
    
```

```{r}
mean_total = estimation %>% 
  group_by(beta1) %>% 
  summarise(mean = mean(estimate)) %>% 
  mutate(category = "total")

mean_reject = estimation %>% 
  filter(p.value <= 0.05) %>% 
  group_by(beta1) %>% 
  summarise(mean = mean(estimate)) %>% 
  mutate(category = "rejected")

g2 <- rbind(mean_total,mean_reject) %>% 
  ggplot(aes(x = beta1, y = mean, color = category)) +
  geom_point() +
  geom_line()+
  labs(y =  "mean of estimation of beta1", title = "Comparison of mean estimation beta1 in total and rejected group.")
g2

  
```


